### ISSUE TITLE
Extension version 1.0.1 not working out of the box

### ISSUE THREAD

**Issue by dsjak-shie** [mollie/commercetools#170] opened 2022-05-11 17:51 UTC
**Deployment**  
_My deployment is on:_

- [ ] Docker
- [ ] AWS Lambda
- [ ] GCP
- [x] Azure
- [ ] Other _Please specify:_

**Expected behaviour**

My function deployed to Azure works.

**Actual behaviour**

The function does not work.

![image](https://user-images.githubusercontent.com/44951819/167913542-01bb34b1-3266-4268-b9d4-ba5ef59815b9.png)

When I unzip the the **extension-module-azure.zip** file and look at the contents of **index.js** I indeed see a couple of require statements pointing to non existing files in the directory structure

![image](https://user-images.githubusercontent.com/44951819/167913944-fa720ce0-2993-4e73-8167-fe0ad6baac5f.png)

![image](https://user-images.githubusercontent.com/44951819/167914318-932e48f2-672a-4fb3-9616-66b99e981646.png)

**Comment by denisand** [comment] 2022-05-13 08:50
I couldn't reproduce. When I unzip the `extension-module-azure.zip`, the folder structure looks like this:

<img width="215" alt="image" src="https://user-images.githubusercontent.com/90899394/168246513-fe723cff-55fb-4200-9a07-a5765eb39b5a.png">

There shouldn't be `build` folder in the zipped version for example.

**Comment by dsjak-shie** [comment] 2022-05-13 14:40
@denisand I'm going to try again. Will let you know

**Comment by dsjak-shie** [comment] 2022-05-13 16:19
@denisand I was able to figure out the problem thanks to your screenshot.

For it to work correctly in my environment I had to modify the following parts of the script:

- `cp -r build/ extension-azure/extension/` ---> `cp -r build/* extension-azure/extension/`
- `cp -r config/azureFunction/ extension-azure/` ---> `cp -r config/azureFunction/* extension-azure/`

**Comment by dsjak-shie** [comment] 2022-05-13 16:41
@denisand next challenge

![image](https://user-images.githubusercontent.com/44951819/168328736-ff3b72f0-5468-4972-9e1e-e53138d41718.png)


It seems the function can't read the settings anymore. This used to work in the initial version. I went to check in the PR and saw that the functionality for loading the settings was removed. Like I said. This got the setting loading job done in the initial release. Why was it removed?

**Comment by denisand** [comment] 2022-05-16 13:40
@dsjak-shie it was removed because it was not necessary, the config should be provided as JSON instead of stringified JSON

**Comment by denisand** [comment] 2022-05-16 15:19
@dsjak-shie I updated the npm command for azure function here https://github.com/mollie/commercetools/pull/171. Feel free to test it.

**Comment by dsjak-shie** [comment] 2022-05-16 17:12
@denisand I checked out your branch and ran the npm command. This now outputs a correctly structured package for me. Thanks for the clarification about the settings, this also works.
I had the settings configured like this for the first version of the integration
![image](https://user-images.githubusercontent.com/44951819/168646530-d78c2eb9-ea70-4272-a8c8-d7d21334d968.png)

That's why I didn't quite understand what needed to happen at first, but I get it now. I just have one setting with key `CT_MOLLIE_CONFIG` where the value is the complete JSON object.
This setup also works with a key vault reference, so I can store the sensitive info securely. 

Thanks for looking into it :)

**Comment by denisand** [comment] 2022-05-17 08:25
Note to self: Before closing the issue, we should check zip commands for lambda and GCP too

**Comment by denisand** [comment] 2022-05-20 10:31
Tested zip commands for lambda and GCP on windows (ubuntu), looks good.

**Closed by denisand** 2022-05-20 10:31 UTC
